version: '3.8'

services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: dataroom-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  minio:
    image: quay.io/minio/minio
    container_name: dataroom-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: dataroom
      MINIO_ROOT_PASSWORD: dataroom
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_data:
  minio_data:
