version: '3.8'

services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: dataroom-mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo_data:
